routes/user.py
from routes import *
from models.log import Log
from models.privilege import Privileges, get_all_privileges
from models.sub_system import SubSystem
from models.parameter import Parameter

main = Blueprint('user', __name__)


@main.route('/login')
def index():
    return render_template('user/login.html')


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    name = form.get('name', '')
    u = User.find_one(name=name)
    if u is not None and u.validate_login(form):
        session['uid'] = u.id
        Log.log(u, '登录账号', request, '[{}] 登录系统'.format(u.name))
        return redirect(url_for('index.index'))
    elif not u:
        flash('此用户未注册', 'warning')
        return redirect(url_for('user.index'))
    else:
        flash('用户名密码错误', 'warning')
        return redirect(url_for('user.index'))


@main.route('/register')
def register_page():
    return render_template('user/register.html')


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    status, msgs = User.valid(form)
    if status is True:
        u = User.new(form)
        session['uid'] = u.id
        flash('注册成功', 'success')
        Log.log(u, '注册账号', request, '[{}] 注册账号'.format(u.mobile))
        return redirect(url_for('user.index'))
    else:
        for msg in msgs:
            flash(msg, 'warning')
        return redirect(url_for('user.register'))


@main.route('/logout')
@login_required
def logout():
    session.pop('uid')
    flash('账号已安全退出', 'success')
    return redirect(url_for('index.index'))


# ------------------------- 权限模块 --------------------------


@main.route('/privilege_list')
@login_required
def privilege_list():
    u = current_user()
    ps = u.privlist
    return render_template('user/privilege_list.html', u=u, ps=ps)


@main.route('/privilege/apply')
@login_required
def privilege_apply_page():
    u = current_user()
    ms = SubSystem.all()
    ps = get_all_privileges()
    return render_template('user/privilege_apply.html', u=u, ms=ms, ps=ps)


@main.route('/privilege/apply', methods=['POST'])
@login_required
def privilege_apply():
    u = current_user()
    ms = SubSystem.all()
    ps = get_all_privileges()
    form = request.form
    return render_template('user/privilege_apply.html', u=u, ms=ms, ps=ps)


# ------------------------- 规程模块 --------------------------


@main.route('/parameters_list')
@login_required
def parameters_list_page():
    u = current_user()
    ms = SubSystem.all()
    ps = Parameter.all()
    return render_template('user/parameter_list.html', u=u, ms=ms, ps=ps)


@main.route('/parameters/add')
@login_required
def parameters_add_page():
    u = current_user()
    ms = SubSystem.all()
    return render_template('user/parameters_add.html', u=u, ms=ms)


@main.route('/parameters/add', methods=['POST'])
@login_required
def parameters_add():
    u = current_user()
    form = request.form
    SubSystem.new(form, creator_uuid=u.uuid)
    return redirect(url_for('user.parameters_list_page'))

templates/base.html
<!DOCTYPE html>
<!--[if IE 8]> <html lang="zh-cmn-Hans" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="zh-cmn-Hans" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="zh-cmn-Hans">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="/static/assets/global/css/fonts.googleapis.com.css" rel="stylesheet" type="text/css">
    <link href="/static/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/static/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css">
    <link href="/static/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <!-- END GLOBAL MANDATORY STYLES -->

    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="/static/assets/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css" rel="stylesheet" type="text/css">
    <link href="/static/assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css">
    <link href="/static/assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css">
    <link href="/static/assets/global/plugins/bootstrap-table/bootstrap-table.min.css" rel="stylesheet" type="text/css">
    <link href="/static/assets/global/plugins/bootstrap-sweetalert/sweetalert.css" rel="stylesheet" type="text/css">
    <link href="/static/assets/global/plugins/bootstrap-fileinput.css" rel="stylesheet" type="text/css">
    <!-- END PAGE LEVEL PLUGINS -->

    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="/static/assets/global/css/components-rounded.min.css" rel="stylesheet" id="style_components" type="text/css">
    <link href="/static/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css">
    <!-- END THEME GLOBAL STYLES -->

    <!-- BEGIN THEME LAYOUT STYLES -->
    <link href="/static/assets/layouts/layout/css/layout.min.css" rel="stylesheet" type="text/css">
    <link href="/static/assets/layouts/layout/css/themes/darkblue.min.css" rel="stylesheet" type="text/css" id="style_color">
    <link href="/static/assets/layouts/layout/css/custom.css" rel="stylesheet" type="text/css">
    <!-- END THEME LAYOUT STYLES -->

    <!-- BEGIN CORE PLUGINS -->
    <script src="/static/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="/static/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/static/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
    <script src="/static/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="/static/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="/static/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->

    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="/static/assets/global/plugins/bootstrap-confirmation/bootstrap-confirmation.min.js" type="text/javascript"></script>
    <script src="/static/assets/global/plugins/bootstrap-table/bootstrap-table.min.js" type="text/javascript"></script>
    <script src="/static/assets/global/plugins/bootstrap-table/bootstrap-table-zh-CN.min.js" type="text/javascript"></script>
    <script src="/static/assets/global/plugins/bootstrap-sweetalert/sweetalert.min.js" type="text/javascript"></script>
    <script src="/static/assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
    <script src="/static/assets/global/plugins/jquery-multi-select/js/jquery.multi-select.js" type="text/javascript"></script>
    <script src="/static/assets/global/plugins/bootstrap-fileinput.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL PLUGINS -->

    <!-- BEGIN THEME GLOBAL SCRIPTS -->
    <script src="/static/assets/global/scripts/app.min.js" type="text/javascript"></script>
    <!-- END THEME GLOBAL SCRIPTS -->

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/static/utils/api.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL SCRIPTS -->

    <!-- BEGIN THEME LAYOUT SCRIPTS -->
    <script src="/static/assets/layouts/layout/scripts/layout.min.js" type="text/javascript"></script>
    <script src="/static/assets/layouts/layout/scripts/demo.min.js" type="text/javascript"></script>
    <script src="/static/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>
    <script src="/static/assets/layouts/global/scripts/quick-nav.min.js" type="text/javascript"></script>
    <!-- END THEME LAYOUT SCRIPTS -->
    <!-- END HEAD -->
</head>

<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white">
<div class="page-wrapper">
    <!-- BEGIN HEADER -->
    <div class="page-header navbar navbar-fixed-top">
        <!-- BEGIN HEADER INNER -->
        <div class="page-header-inner ">
            {% block header %}
                {% include 'header.html' %}
            {% endblock %}
        </div>
        <!-- END HEADER INNER -->
    </div>
    <!-- END HEADER -->
    <!-- BEGIN HEADER & CONTENT DIVIDER -->
    <div class="clearfix"></div>
    <!-- END HEADER & CONTENT DIVIDER -->
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        <!-- BEGIN SIDEBAR -->
        {% block sidebar %}
            {% include 'sidebar.html' %}
        {% endblock %}
        <!-- END SIDEBAR -->
        <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <!-- BEGIN CONTENT BODY -->
            <div class="page-content">
                <!-- BEGIN PAGE HEADER-->
                <div class="container-fluid alert-container">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                            aria-hidden="true">×</span></button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                </div>
                <script>
                    $(document).ready(function () {
                            $('.alert').delay(3000).fadeOut(600)
                        },
                    )
                </script>

                {% block body %}
                {% endblock %}
            </div>
            <!-- END CONTENT BODY -->
        </div>
        <!-- END CONTENT -->
    </div>
    <!-- END CONTAINER -->
    <!-- BEGIN FOOTER -->
    {% block footer %}
        {% include 'footer.html' %}
    {% endblock %}

    <!-- END FOOTER -->
</div>
</body>

<script>
    // 解决前端兼容性 使得各个浏览器均可以选择日期
    const ds = $("input[type='date']")
    ds.prop('type', 'text')
    ds.prop('readonly', 'readonly')
    ds.datepicker({
        format: 'yyyy-mm-dd',
        language: 'zh-CN',
        autoclose: true,
        immediateUpdates: true,
        forceParse: false,
    })
</script>
</html>

templates/footer.html
<div class="page-footer">
    <div class="page-footer-inner"> 2018 &copy; DataMS project By
        <a href="#">Yuanxiaoyang Group</a> &nbsp;|&nbsp;
        <a href="#">面向对象</a>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>

templates/header.html
<!-- BEGIN LOGO -->
<div class="page-logo">
	<a href="{{ url_for('index.index') }}"></a>
	<div class="menu-toggler sidebar-toggler">
		<span></span>
	</div>
</div>
<!-- END LOGO -->
<!-- BEGIN RESPONSIVE MENU TOGGLER -->
<a href="javascript:" class="menu-toggler responsive-toggler" data-toggle="collapse"
   data-target=".navbar-collapse">
	<span></span>
</a>
<!-- END RESPONSIVE MENU TOGGLER -->
<!-- BEGIN TOP NAVIGATION MENU -->
<div class="top-menu">
	<ul class="nav navbar-nav pull-right">
		<!-- BEGIN NOTIFICATION DROPDOWN -->
		<li class="dropdown dropdown-user">
			<a href="javascript:" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
			   data-close-others="true">
				{% if u %}
					<img alt="" class="img-circle" src="/static/assets/layouts/layout/img/avatar3_small.jpg"/>
					{% set u = g.user %}
					<span class="username username-hide-on-mobile"> {% if u %} {{ u.name }} {% endif %}</span>
					<i class="fa fa-angle-down"></i>
					</a>

					<ul class="dropdown-menu dropdown-menu-default">
						<li>
							<a href="#">
								<i class="icon-key"></i> 修改密码 </a>
						</li>
						<li class="divider"></li>
						<li>
							<a href="{{ url_for('user.logout') }}">
								<i class="icon-power"></i> 登出 </a>
						</li>
					</ul>
					</li>
					<!-- END USER LOGIN DROPDOWN -->
					<!-- BEGIN QUICK SIDEBAR TOGGLER -->
					<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
					<li class="dropdown dropdown-quick-sidebar-toggler">
						<a href="{{ url_for('user.logout') }}" class="dropdown-toggle">
							<i class="icon-logout"></i>
						</a>
					</li>
				{% endif %}
		<!-- END QUICK SIDEBAR TOGGLER -->
	</ul>
</div>
<!-- END TOP NAVIGATION MENU -->

templates/index.html
{% extends 'base.html' %}
{% block body %}
	<!-- BEGIN PAGE BAR -->
	<div class="page-bar">
		<ul class="page-breadcrumb">
			<li>
				<a class="active" href="{{ url_for('index.index') }}">Home</a>
				<i class="fa fa-angle-right"></i>
			</li>
		</ul>
	</div>
	<div class="portlet light bordered">
		<div class="portlet-title">
			<div class="caption">
				<i class="icon-bubble font-green-sharp"></i>
				<span class="caption-subject font-green-sharp sbold">待处理流程</span>
			</div>

		</div>
		<div class="portlet-body">

		</div>
	</div>

	<div class="portlet light bordered">
		<div class="portlet-title">
			<div class="caption">
				<i class="icon-bubble font-green-sharp"></i>
				<span class="caption-subject font-green-sharp sbold">登录信息</span>
			</div>

		</div>
		<div class="portlet-body">

			<table class="table " data-toggle="table" id="log-table" data-pagination="true" data-page-size="10">
				<thead>
				<tr>
					<th class="th-col-1">操作账号</th>
					<th class="th-col-1">操作模块</th>
					<th class="th-col-1">操作系统</th>
					<th class="th-col-1">操作ip</th>
					<th class="th-col-1">浏览器</th>
					<th class="th-col-2">时间</th>
				</tr>
				</thead>
				<tbody>
				{% for m in ms %}
					<tr data-id={{ m.id }}>
						<td>{{ m.user_name }}</td>
						<td>{{ m.action }}</td>
						<td>{{ m.platform }}</td>
						<td>{{ m.ip }}</td>
						<td>{{ m.browser }}</td>
						<td>{{ m.ct | time_str }}</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>

		</div>
	</div>

{% endblock %}

templates/sidebar.html
<div class="page-sidebar-wrapper">
	<!-- BEGIN SIDEBAR -->
	<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
	<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
	<div class="page-sidebar navbar-collapse collapse">
		<!-- BEGIN SIDEBAR MENU -->
		<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
		<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
		<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
		<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true"
			data-slide-speed="200" style="padding-top: 20px">
			<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
			<li class="sidebar-toggler-wrapper hide">
				<div class="sidebar-toggler">
					<span></span>
				</div>
			</li>
			<!-- END SIDEBAR TOGGLER BUTTON -->
			<!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
			{% set u = g.user %}
			{% if u %}

				<li class="nav-item start">
					<a href="javascript:" class="nav-link nav-toggle">
						<i class="icon-graduation"></i>
						<span class="title">权限管理</span>
						<span class="arrow"></span>
					</a>
					{% if not u.is_admin() %}
						<ul class="sub-menu">
							<li class="nav-item ">
								<a href="{{ url_for('user.privilege_list') }}" class="nav-link ">
									<i class="icon-list"></i>
									<span class="title">我的权限</span>
								</a>
							</li>
							<li class="nav-item ">
								<a href="{{ url_for('user.privilege_apply_page') }}" class="nav-link ">
									<i class="icon-plus"></i>
									<span class="title">权限申请</span>
								</a>
							</li>
						</ul>
					{% else %}
						<ul class="sub-menu">
							<li class="nav-item ">
								<a href="{{ url_for('user.privilege_list') }}" class="nav-link ">
									<i class="icon-list"></i>
									<span class="title">我的权限</span>
								</a>
							</li>
							<li class="nav-item ">
								<a href="#" class="nav-link ">
									<i class="icon-check"></i>
									<span class="title">待批准权限</span>

								</a>
							</li>
						</ul>
					{% endif %}
				</li>
				<li class="nav-item start">
					<a href="javascript:" class="nav-link nav-toggle">
						<i class="icon-graduation"></i>
						<span class="title">规程操作</span>
						<span class="arrow"></span>
					</a>
					<ul class="sub-menu">
						<li class="nav-item ">
							<a href="{{ url_for('user.parameters_list_page') }}" class="nav-link ">
								<i class="icon-list"></i>
								<span class="title">参数列表</span>
							</a>
						</li>
						<li class="nav-item ">
							<a href="{{ url_for('user.parameters_add') }}" class="nav-link ">
								<i class="icon-note"></i>
								<span class="title">录入参数</span>

							</a>
						</li>
						<li class="nav-item ">
							<a href="#" class="nav-link ">
								<i class="icon-pie-chart"></i>
								<span class="title">规程统计</span>

							</a>
						</li>
					</ul>
				</li>

				<li class="nav-item start">
					<a href="javascript:" class="nav-link nav-toggle">
						<i class="icon-graduation"></i>
						<span class="title">分系统信息</span>
						<span class="arrow"></span>
					</a>
					<ul class="sub-menu">
						<li class="nav-item ">
							<a href="{{ url_for('sub_system.sub_system_list_page') }}" class="nav-link ">
								<i class="icon-list"></i>
								<span class="title">分系统列表</span>
							</a>
						</li>
					</ul>
				</li>
				{% if u.is_admin() %}
					<li class="nav-item start">
						<a href="javascript:" class="nav-link nav-toggle">
							<i class="icon-graduation"></i>
							<span class="title">人员管理</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub-menu">
							<li class="nav-item ">
								<a href="{{ url_for('admin.user_list') }}" class="nav-link ">
									<i class="icon-list"></i>
									<span class="title">人员列表</span>
								</a>
							</li>
						</ul>
					</li>
				{% endif %}
			{% endif %}
		</ul>
		<!-- END SIDEBAR MENU -->
		<!-- END SIDEBAR MENU -->
	</div>
	<!-- END SIDEBAR -->
</div>