models/user.py
__author__ = 'nickyuan'
import hashlib
from models import MongoModel


class User(MongoModel):
    @classmethod
    def _fields(cls):
        fields = [
            # 账号
            ('name', str, ''),
            # 姓名
            ('username', str, ''),
            # 登录密码
            ('password', str, ''),
            # 用户角色, 'admin'/'manager'/'user'/'t_1--t_3'
            ('role', str, 'user'),

            # 权限列表
            ('privlist', dict, {}),
            # 进程列表
            ('proclist', list, []),
            # 用户密码的盐、
            ('salt', str, '123456'),

        ]
        fields.extend(super()._fields())
        return fields

    @classmethod
    def get_username(cls, uuid):
        user = cls.get_uuid(uuid)
        if user is not None:
            return user.username
        else:
            return ''

    @classmethod
    def new(cls, form, **kwargs):
        m = super().new(form, **kwargs)
        m.password = m.salted_password(form.get('password', ''))
        m.save()
        return m

    def validate_login(self, form):
        password = form.get('password', '')
        password = self.salted_password(password)
        return password == self.password

    def salted_password(self, password):
        salt = self.salt
        hash1 = hashlib.sha1(password.encode('ascii')).hexdigest()
        hash2 = hashlib.sha1((hash1 + salt).encode('ascii')).hexdigest()
        return hash2

    @classmethod
    def valid(cls, form):
        name = form.get('name', '')
        password = form.get('password', '')
        valid_user = cls.find_one(name=name) is None
        valid_password = len(password) >= 3
        msgs = []
        if not valid_user:
            message = '用户名已存在'
            msgs.append(message)
        if not valid_password:
            message = '密码至少需要三位数'
            msgs.append(message)
        status = valid_user and valid_password
        return status, msgs

    def is_admin(self):
        return self.role == '管理员'

    # 总师 -- 批准权限
    def is_t_1(self):
        return self.role == '总师' or self.is_admin()

    # 指挥 -- 一级审核权限
    def is_t_2(self):
        return self.role == '测试指挥' or self.is_t_1()

    # 总体 -- 二级审核权限
    def is_t_3(self):
        return self.role == '测试总体' or self.is_t_2()

    # 判读人员 -- 普通校对权限
    def is_user(self):
        return self.role == '判读人员'

    @classmethod
    def insert_admin(cls):
        u = User.find_one(name='admin')
        if not u:
            form = {
                'name': 'admin',
                'username': 'admin',
                'role': '管理员',
                'password': '123456',
            }
            cls.new(form, privlist={'测试系统一': ['edit', 'revision', 'audit', 'approve'],
                                    '测试系统二': ['edit'],
                                    '测试系统三': ['edit'],
                                    '测试系统四': ['edit']
                                    },
                    proclist=[])

routes/sub_system.py
__author__ = 'nickyuan'
from routes import *
from models.sub_system import SubSystem

main = Blueprint('sub_system', __name__)


@main.route('/list')
@login_required
def sub_system_list_page():
    u = current_user()
    systems = SubSystem.all()
    return render_template('user/sub_system_list.html', u=u, systems=systems)


@main.route('/sub_system/add', methods=['POST'])
@admin_required
def sub_system_add():
    u = current_user()
    form = request.form
    SubSystem.new(form, creator_uuid=u.uuid)
    return redirect(url_for('sub_system.sub_system_list_page'))


@main.route('/sub_system/del/<uuid>')
@admin_required
def sub_system_del(uuid):
    m = SubSystem.get_uuid(uuid)
    m.delete()
    flash('删除成功', 'success')
    return redirect(url_for('sub_system.sub_system_list_page'))

routes/user.py
from routes import *
from models.log import Log
from models.privilege import Privileges, get_all_privileges
from models.sub_system import SubSystem
from models.parameter import Parameter

main = Blueprint('user', __name__)


@main.route('/login')
def index():
    return render_template('user/login.html')


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    name = form.get('name', '')
    u = User.find_one(name=name)
    if u is not None and u.validate_login(form):
        session['uid'] = u.id
        Log.log(u, '登录账号', request, '[{}] 登录系统'.format(u.name))
        return redirect(url_for('index.index'))
    elif not u:
        flash('此用户未注册', 'warning')
        return redirect(url_for('user.index'))
    else:
        flash('用户名密码错误', 'warning')
        return redirect(url_for('user.index'))


@main.route('/register')
def register_page():
    return render_template('user/register.html')


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    status, msgs = User.valid(form)
    if status is True:
        u = User.new(form)
        session['uid'] = u.id
        flash('注册成功', 'success')
        Log.log(u, '注册账号', request, '[{}] 注册账号'.format(u.mobile))
        return redirect(url_for('user.index'))
    else:
        for msg in msgs:
            flash(msg, 'warning')
        return redirect(url_for('user.register'))


@main.route('/logout')
@login_required
def logout():
    session.pop('uid')
    flash('账号已安全退出', 'success')
    return redirect(url_for('index.index'))


# ------------------------- 权限模块 --------------------------


@main.route('/privilege_list')
@login_required
def privilege_list():
    u = current_user()
    ps = u.privlist
    return render_template('user/privilege_list.html', u=u, ps=ps)


@main.route('/privilege/apply')
@login_required
def privilege_apply_page():
    u = current_user()
    ms = SubSystem.all()
    ps = get_all_privileges()
    return render_template('user/privilege_apply.html', u=u, ms=ms, ps=ps)


@main.route('/privilege/apply', methods=['POST'])
@login_required
def privilege_apply():
    u = current_user()
    ms = SubSystem.all()
    ps = get_all_privileges()
    form = request.form
    return render_template('user/privilege_apply.html', u=u, ms=ms, ps=ps)


# ------------------------- 规程模块 --------------------------


@main.route('/parameters_list')
@login_required
def parameters_list_page():
    u = current_user()
    ms = SubSystem.all()
    ps = Parameter.all()
    return render_template('user/parameter_list.html', u=u, ms=ms, ps=ps)


@main.route('/parameters/add')
@login_required
def parameters_add_page():
    u = current_user()
    ms = SubSystem.all()
    return render_template('user/parameters_add.html', u=u, ms=ms)


@main.route('/parameters/add', methods=['POST'])
@login_required
def parameters_add():
    u = current_user()
    form = request.form
    SubSystem.new(form, creator_uuid=u.uuid)
    return redirect(url_for('user.parameters_list_page'))

templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1" name="viewport"/>
	<meta content="Preview page of Metronic Admin Theme #1 for " name="description"/>
	<meta content="" name="author"/>
	<link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css"/>
	<!-- BEGIN THEME GLOBAL STYLES -->
	<link href="/static/assets/global/css/components-rounded.min.css" rel="stylesheet" id="style_components"
		  type="text/css"/>
	<link href="/static/assets/pages/css/login.min.css" rel="stylesheet" type="text/css"/>
	<script src="/static/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
	<script src="/static/assets/global/scripts/app.min.js" type="text/javascript"></script>
	<script src="/static/assets/layouts/layout/scripts/layout.min.js" type="text/javascript"></script>
	<script src="/static/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="/static/assets/global/plugins/jquery.backstretch.min.js" type="text/javascript"></script>
<body class="login" data-channel="public">
<div class="user-login-5">
	<div class="row bs-reset">
		<div class="col-md-6 bs-reset mt-login-5-bsfix">
			<div class="login-bg" style="background-image:url(/static/assets/pages/img/login/bg1.jpg)">
			</div>
		</div>
		<div class="col-md-6 login-container bs-reset mt-login-5-bsfix">
			<div class="login-content portlet-body form">
				<form role="form" action="{{ url_for('user.login') }}" class="login-form form-user" method="post"
					  data-type="login">
					<div class="form-body">
						<div class="row">
							<div class="container-fluid alert-container">
								{% with messages = get_flashed_messages(with_categories=true) %}
									{% if messages %}
										{% for category, message in messages %}
											<div class="alert alert-{{ category }} alert-dismissible" role="alert">
												<button type="button" class="close" data-dismiss="alert"
														aria-label="Close"><span
														aria-hidden="true">×</span></button>
												{{ message }}
											</div>
										{% endfor %}
									{% endif %}
								{% endwith %}
							</div>

						</div>
						<h3>用户登录</h3>
						<br>
						<br>
						<div class="row">
							<div class="col-xs-6">
								<div class="form-group form-md-line-input form-md-floating-label">
									<input class="form-control" type="text" autocomplete="off" name="name"
										   id="id-input-username" required/>
									<label for="id-input-username">用户名</label>
									<span class="help-block">请输入用户名</span>
								</div>
							</div>
							<div class="col-xs-6">
								<div class="form-group form-md-line-input form-md-floating-label">
									<input class="form-control" type="password" autocomplete="off" name="password"
										   id="id-input-password" required/>
									<label for="id-input-password">密码</label>
									<span class="help-block">请输入密码</span>
								</div>
							</div>
						</div>
					</div>
					<div class="form-actions noborder">
						<div class="col-sm-4">
						</div>
						<div class="col-sm-8 text-right">
							<button class="btn green" type="submit">Sign In</button>
							<a href="{{ url_for('user.register_page') }}">
								<button class="btn green" type="button" onclick="">Register</button>
							</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
    $('.login-bg').backstretch([
            "/static/assets/pages/img/login/bg1.jpg",
            "/static/assets/pages/img/login/bg2.jpg",
            "/static/assets/pages/img/login/bg3.jpg",
            "/static/assets/pages/img/login/bg4.jpg",
        ], {
            fade: 1000,
            duration: 8000
        }
    )
</script>
</body>

</html>

templates/user/my_process.html
{% extends 'base.html' %}
{% block body %}
	<div class="page-bar">
		<ul class="page-breadcrumb">
			<li>
				<a href="{{ url_for('index.index') }}">Home</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="{{ url_for('user.parameters_list_page') }}">我的流程</a>
			</li>
		</ul>
	</div>

	<h1 class="page-title">
		<i class="icon-list font-green"></i>
		<span class="caption-subject font-green sbold uppercase">我的流程</span>
	</h1>

	<a href="{{ url_for('user.parameters_add_page') }}">
		<button class="btn green right">启动流程
			<i class="fa fa-plus"></i>
		</button>
	</a>

	<form class="navbar-form px-0" action="{{ url_for('user.parameters_list_page') }}">
		<div class="th-col-1">
			<input type="text" class="form-control" name="name" placeholder="请输入参数名称" id="keyword">
			<button type="submit" class="btn btn-default">查询 <i class="fa fa-search"></i></button>
		</div>
	</form>

	<div class="portlet-body">

		<table class="table " data-toggle="table" id="log-table" data-pagination="true" data-page-size="10">
			<thead>
			<tr>
				<th class="th-col-2" data-sortable="true">分系统</th>
				<th class="th-col-2" data-sortable="true">规程名</th>
				<th class="th-col-2" data-sortable="true">规程参数</th>
				<th class="th-col-6" data-sortable="true">操作</th>
			</tr>
			</thead>
			<tbody>
			{% for m in ms %}
				{% if m.editable(u) %}
					{% for p in ps %}
						{% if p.sub_system_uuid == m.uuid %}
							<tr data-id={{ m.id }}>
								<td>{{ m.sys_name }}</td>
								<td>{{ p.name }}</td>
								<td>{{ p.value }}</td>
								<td>
									<a href="{{ url_for('admin.course', uuid=m.uuid) }}"
									   class="btn green-haze btn-outline sbold btn-sm"><i
											class="fa fa-edit"></i> 修改 </a>
									<a href="{{ url_for('manager.training_homework_list') }}"
									   class="btn blue-hoki btn-outline sbold btn-sm"><i
											class="fa fa-comment-o"></i> 批注 </a>
									<a href="{{ url_for('admin.course_update_page', uuid=m.uuid) }}"
									   class="btn grey-mint btn-outline sbold btn-sm"><i
											class="fa fa-comments-o"></i>查看批注</a>
								</td>
							</tr>
						{% endif %}
					{% endfor %}
				{% endif %}
			{% endfor %}
			</tbody>
		</table>

	</div>

{% endblock %}

templates/user/parameter_list.html
{% extends 'base.html' %}
{% block body %}
	<div class="page-bar">
		<ul class="page-breadcrumb">
			<li>
				<a href="{{ url_for('index.index') }}">Home</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="{{ url_for('user.parameters_list_page') }}">规程列表</a>
			</li>
		</ul>
	</div>

	<h1 class="page-title">
		<i class="icon-list font-green"></i>
		<span class="caption-subject font-green sbold uppercase">规程列表</span>
	</h1>

	<a href="{{ url_for('user.parameters_add_page') }}">
		<button class="btn green right">录入参数
			<i class="fa fa-plus"></i>
		</button>
	</a>

	<form class="navbar-form px-0" action="{{ url_for('user.parameters_list_page') }}">
		<div class="th-col-1">
			<input type="text" class="form-control" name="name" placeholder="请输入参数名称" id="keyword">
			<button type="submit" class="btn btn-default">查询 <i class="fa fa-search"></i></button>
		</div>
	</form>

	<div class="portlet-body">

		<table class="table " data-toggle="table" id="log-table" data-pagination="true" data-page-size="10">
			<thead>
			<tr>
				<th class="th-col-2" data-sortable="true">分系统</th>
				<th class="th-col-2" data-sortable="true">规程名</th>
				<th class="th-col-2" data-sortable="true">规程参数</th>
				<th class="th-col-6" data-sortable="true">操作</th>
			</tr>
			</thead>
			<tbody>
			{% for m in ms %}
				{% if m.editable(u) %}
					{% for p in ps %}
						{% if p.sub_system_uuid == m.uuid %}
							<tr data-id={{ m.id }}>
								<td>{{ m.sys_name }}</td>
								<td>{{ p.name }}</td>
								<td>{{ p.value }}</td>
								<td>
									<a href="{{ url_for('admin.course', uuid=m.uuid) }}"
									   class="btn green-haze btn-outline sbold btn-sm"><i
											class="fa fa-edit"></i> 修改 </a>
									<a href="{{ url_for('manager.training_homework_list') }}"
									   class="btn blue-hoki btn-outline sbold btn-sm"><i
											class="fa fa-comment-o"></i> 批注 </a>
									<a href="{{ url_for('admin.course_update_page', uuid=m.uuid) }}"
									   class="btn grey-mint btn-outline sbold btn-sm"><i
											class="fa fa-comments-o"></i>查看批注</a>
								</td>
							</tr>
						{% endif %}
					{% endfor %}
				{% endif %}
			{% endfor %}
			</tbody>
		</table>

	</div>

{% endblock %}

templates/user/parameters_add.html
{% extends 'base.html' %}
{% block body %}
	<div class="page-bar">
		<ul class="page-breadcrumb">
			<li>
				<a href="{{ url_for('index.index') }}">Home</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li><span>录入规程</span></li>
		</ul>
	</div>

	<h1 class="page-title">
		<i class="icon-note font-green"></i>
		<span class="caption-subject font-green sbold uppercase">录入规程</span>
	</h1>

	<div class="portlet light bordered">
		<div class="portlet-body">
			<div class="form-horizontal">
				<form method=POST enctype=multipart/form-data
					  action="{{ url_for('user.parameters_add') }}">
					<div class="form-group form-md-line-input">
						<label class="col-md-2 control-label" for="form_control_2">分系统</label>
						<div class="col-md-10">
							<select required class="form-control" name="category" id="form_control_2">
								<option value="">请选择系统</option>
								{% for m in ms %}
									{% if m.editable(u) %}
										<option value="{{ m.sys_name }}">{{ m.sys_name }}</option>
									{% endif %}
								{% endfor %}
							</select>
							<div class="form-control-focus"></div>
						</div>
					</div>

					<div class="form-group form-md-line-input">
						<label class="col-md-2 control-label" for="form_control_1">规程名称</label>
						<div class="col-md-10">
							<input required type="text" class="form-control" name="name" autocomplete="off"
								   id="form_control_1"
								   placeholder="请输入规程名">
							<div class="form-control-focus"></div>
							<span class="help-block"><span class="label label-sm label-danger">必填</span> 请输入规程名</span>
						</div>
					</div>

					<div class="form-group form-md-line-input">
						<label class="col-md-2 control-label" for="form_control_1">规程参数</label>
						<div class="col-md-10">
							<input required type="text" class="form-control" name="name" autocomplete="off"
								   id="form_control_1"
								   placeholder="请输入规程参数">
							<div class="form-control-focus"></div>
							<span class="help-block"><span class="label label-sm label-danger">必填</span> 请输入规程参数</span>
						</div>
					</div>

					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-5 col-md-3">
								<a class="btn default" type="button"
								   href="{{ url_for('user.parameters_list_page') }}">&nbsp;&nbsp;取消&nbsp;&nbsp;
								</a>
								<button class="btn green" type="submit">发起申请</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

{% endblock %}

templates/user/privilege_apply.html
{% extends 'base.html' %}
{% block body %}
	<div class="page-bar">
		<ul class="page-breadcrumb">
			<li>
				<a href="{{ url_for('index.index') }}">Home</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li><span>申请权限</span></li>
		</ul>
	</div>

	<h1 class="page-title">
		<i class="icon-note font-green"></i>
		<span class="caption-subject font-green sbold uppercase">申请权限</span>
	</h1>

	<div class="portlet light bordered">
		<div class="portlet-body">
			<div class="form-horizontal">
				<form method=POST enctype=multipart/form-data
					  action="{{ url_for('user.privilege_apply') }}">
					<div class="form-group form-md-line-input">
						<label class="col-md-2 control-label" for="form_control_2">申请系统</label>
						<div class="col-md-10">
							<select required class="form-control" name="category" id="form_control_2">
								<option value="">请选择系统</option>
								{% for m in ms %}
									<option value="{{ m.sys_name }}">{{ m.sys_name }}</option>
								{% endfor %}
							</select>
							<div class="form-control-focus"></div>
						</div>
					</div>
					<div class="form-group form-md-line-input">
						<label class="col-md-2 control-label" for="form_control_2">申请权限</label>
						<div class="col-md-10">
							<select required class="form-control" name="category" id="form_control_2">
								<option value="">请选择权限</option>
								{% for p in ps %}
									<option value="{{ p.name }}">{{ p.name | priv_name }}</option>
								{% endfor %}
							</select>
							<div class="form-control-focus"></div>
						</div>
					</div>
					<div class="form-group form-md-line-input">
						<label class="col-md-2 control-label" for="form_control_1">申请原因</label>
						<div class="col-md-10">
                            <textarea required type="text" class="form-control" name="introduction" autocomplete="off"
									  id="form_control_3" rows="2" maxlength="200"
									  placeholder="申请原因，少于200字"></textarea>
							<div class="form-control-focus"></div>
							<span class="help-block"><span class="label label-sm label-danger">必填</span> 请输入申请原因</span>
						</div>
					</div>

					<div class="form-actions">
						<div class="row">
							<div class="col-md-offset-5 col-md-3">
								<a class="btn default" type="button"
								   href="{{ url_for('user.privilege_list') }}">&nbsp;&nbsp;取消&nbsp;&nbsp;
								</a>
								<button class="btn green" type="submit">发起申请</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

{% endblock %}

templates/user/privilege_list.html
{% extends 'base.html' %}
{% block body %}
	<div class="page-bar">
		<ul class="page-breadcrumb">
			<li>
				<a href="{{ url_for('index.index') }}">Home</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="{{ url_for('user.privilege_list') }}">我的权限</a>
			</li>
		</ul>
	</div>

	<h1 class="page-title">
		<i class="icon-list font-green"></i>
		<span class="caption-subject font-green sbold uppercase">我的权限</span>
	</h1>
	{% if not u.is_admin() %}
		<a href="{{ url_for('user.privilege_apply_page') }}">
			<button class="btn green right">申请权限
				<i class="fa fa-plus"></i>
			</button>
		</a>
	{% endif %}
	<form class="navbar-form px-0" action="{{ url_for('user.privilege_list') }}">
		<div class="th-col-1">
			<input type="text" class="form-control" name="name" placeholder="请输入分系统名称" id="keyword">
			<button type="submit" class="btn btn-default">查询 <i class="fa fa-search"></i></button>
		</div>
	</form>

	<div class="portlet-body">

		<table class="table " data-toggle="table" id="log-table" data-pagination="true" data-page-size="10">
			<thead>
			<tr>
				<th class="th-col-2" data-sortable="true">分系统</th>
				<th class="th-col-2" data-sortable="true">权限</th>
			</tr>
			</thead>
			<tbody>
			{% for p in ps %}
				{% for k in ps[p] %}
					<tr data-id={{ p.id }}>
						<td>{{ p }}</td>
						<td>{{ k | priv_name }}</td>
					</tr>
				{% endfor %}
			{% endfor %}
			</tbody>
		</table>

	</div>

{% endblock %}

templates/user/process_add.html
<div class="row step-line">
	<div class="mt-step-desc">
		<div class="font-dark bold uppercase">4 Steps Line</div>
		<div class="caption-desc font-grey-cascade"> 4 Steps Numbered Line element style. Activate by adding
			<pre class="mt-code">.step-line</pre>
			class to the
			<pre class="mt-code">.row</pre>
			element.
			<pre class="mt-code">.first</pre>
			and
			<pre class="mt-code">.last</pre>
			classes are required to be added into
			<pre class="mt-code">.mt-step-col</pre>
			to indicate the first and last step.
		</div>
		<br></div>
	<div class="col-md-3 mt-step-col first done">
		<div class="mt-step-number bg-white">1</div>
		<div class="mt-step-title uppercase font-grey-cascade">Setup</div>
		<div class="mt-step-content font-grey-cascade">Lorem ipsum dolor sit amet</div>
	</div>
	<div class="col-md-3 mt-step-col done">
		<div class="mt-step-number bg-white">2</div>
		<div class="mt-step-title uppercase font-grey-cascade">Develop</div>
		<div class="mt-step-content font-grey-cascade">Lorem ipsum dolor sit amet</div>
	</div>
	<div class="col-md-3 mt-step-col active">
		<div class="mt-step-number bg-white">3</div>
		<div class="mt-step-title uppercase font-grey-cascade">Testing</div>
		<div class="mt-step-content font-grey-cascade">Lorem ipsum dolor sit amet</div>
	</div>
	<div class="col-md-3 mt-step-col last">
		<div class="mt-step-number bg-white">4</div>
		<div class="mt-step-title uppercase font-grey-cascade">Launch</div>
		<div class="mt-step-content font-grey-cascade">Lorem ipsum dolor sit amet</div>
	</div>
</div>

templates/user/sub_system_list.html
{% extends 'base.html' %}
{% block body %}
	<div class="page-bar">
		<ul class="page-breadcrumb">
			<li>
				<a href="{{ url_for('index.index') }}">Home</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<span>分系统列表</span>
			</li>
		</ul>
	</div>

	<h1 class="page-title">
		<i class="icon-list font-green"></i>
		<span class="caption-subject font-green sbold uppercase">分系统列表</span>
	</h1>
	{% if u.is_admin() %}
		<button data-toggle="modal"
				data-target="#id-modal-system-add" class="btn green right">新增分系统
			<i class="fa fa-plus"></i>
		</button>
	{% endif %}
	<form class="navbar-form px-0" action="{{ url_for('sub_system.sub_system_list_page') }}">
		<div class="th-col-1">
			<input type="text" class="form-control" name="name" placeholder="请输入分系统名称" id="keyword">
			<button type="submit" class="btn btn-default">查询 <i class="fa fa-search"></i></button>
		</div>
	</form>

	<div class="portlet-body">

		<table class="table " data-toggle="table" id="log-table" data-pagination="true" data-page-size="10">
			<thead>
			<tr>
				<th class="th-col-2">分系统名称</th>
				<th class="th-col-2">创建人</th>
				<th class="th-col-3">创建时间</th>
				<th class="th-col-4">操作</th>
			</tr>
			</thead>
			<tbody>
			{% for system in systems %}
				<tr data-id={{ system.id }}>
					<td>{{ system.sys_name }}</td>
					<td>{{ system.creator }}</td>
					<td>{{ system.ct | time_str }}</td>
					<td>
						<a href="javascript:"
						   class="btn blue-hoki btn-outline sbold uppercase btn-sm"><i
								class="fa fa-book"></i>查看参数</a>
						{% if u.is_admin() %}
							<button data-toggle="modal"
									data-target="#id-modal-system-add"
									class="btn grey-mint btn-outline sbold uppercase btn-sm"><i
									class="fa fa-plus"></i>添加参数
							</button>
							<a href="javascript:"
							   onclick="sub_system_del('{{ system.sys_name }}', '{{ system.uuid }}')"
							   class="btn red-mint btn-outline sbold btn-sm course_delete"><i
									class="fa fa-trash"></i> 删除</a>
						{% endif %}
					</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>

	</div>
	<div id="id-modal-system-add" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button class="close" data-dismiss="modal"></button>
					<h4 class="modal-title">请设置分系统基础信息</h4>
				</div>
				<form method="POST" enctype="multipart/form-data" action="{{ url_for('sub_system.sub_system_add') }}">
					<div class="modal-body">
						<div class="form-group">
							<label><span class="font-red">*</span>分系统名称</label>
							<input name="sys_name" type="text"
								   autocomplete="off"
                                   placeholder="请输入分系统名"
								   class="form-control">
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn dark btn-outline" data-dismiss="modal">关闭</button>
						<button type="submit" class="btn green">保存</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	<script>
        let sub_system_del = function (name, uuid) {
            swal({
                    title: `确定删除 "${name}" 吗？`,
                    text: "该操作无法恢复！",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "确定删除！",
                    cancelButtonText: '取消',
                    closeOnConfirm: false,
                },
                function () {
                    $.get(`/sub_system/sub_system/del/${uuid}`)
                        .done(function () {
                            swal({
                                title: "成功！",
                                text: "删除：" + name,
                                type: "success",
                                timer: 600,
                            }, function () {
                                location.reload()
                            })
                        })
                        .fail(function (xhr, status, error) {
                            swal({
                                title: "错误！",
                                text: "服务器响应：" + error,
                                type: "error",
                            }, function () {
                                location.reload()
                            })
                        })
                })
        }
	</script>
{% endblock %}